name: Build
on:
  pull_request:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build-server:
    runs-on: ubuntu-latest
    name: Build
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Ruby (for fpm)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install fpm
        run: |
          gem install fpm

      - name: Build binary & Debian package
        run: |
          make build debian

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: "*.deb"

      - name: Log in to the GitHub container registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/kastelo/syncthing-configd:latest
